# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Diogo Monte"
description: > # this means to ignore newlines until "email:"
   Welcome to my github page.

email: monte.diogo@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Diogo Monte'
author: 'Diogo Monte'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@diogo_monte'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/diogo_monte
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/diogomonte
    desc:	My github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
